INSERT INTO skills (name)
VALUES ('Athletics'),
('Acrobatics'),
('Slight of Hand'),
('Stealth'),
('Arcana'),
('History'),
('Investigation'),
('Nature'),
('Religion'),
('Animal Handling'),
('Insight'),
('Medicine'),
('Perception'),
('Survival'),
('Deception'),
('Intimidation'),
('Performance'),
('Persuasion');

INSERT INTO attributes (name)
VALUES ('Strength'),
('Dexterity'),
('Intelligence'),
('Wisdom'),
('Charisma');

INSERT INTO class (name)
VALUES ('Barbarian'),
('Bard'),
('Cleric'),
('Druid'),
('Fighter'),
('Monk'),
('Paladin'),
('Ranger'),
('Rogue'),
('Sorcerer'),
('Warlock'),
('Wizard');

INSERT INTO race (name)
VALUES ('Human'),
('Elf'),
('Drow'),
('Half-Elf'),
('Half-Orc'),
('Halfling'),
('Dwarf'),
('Gnome'),
('Tiefling'),
('Githyanki'),
('Dragonborn');

INSERT INTO subrace (name)
VALUES ('High Elf'),
('Wood Elf'),
('Lolth-sworn Drow'),
('Seldarine Drow'),
('High Half-Elf'),
('Wood Half-Elf'),
('Drow Half-Elf'),
('Lightfoot Halfling'),
('Strongheart Halfling'),
('Gold Dwarf'),
('Shield Dwarf'),
('Duergar Dwarf'),
('Forest Gnome'),
('Deep Gnome'),
('Rock Dwarf'),
('Asmodeus Tiefling'),
('Mephistopheles Tiefling'),
('Zariel Tiefling'),
('Black Dragonborn'),
('BLue Dragonborn'),
('Brass Dragonborn'),
('Bronze Dragonborn'),
('Copper Dragonborn'),
('Gold Dragonborn'),
('Green Dragonborn'),
('Red Dragonborn'),
('Silver Dragonborn'),
('White Dragonborn');

INSERT INTO backgrounds (name, description)
VALUES ('Acolyte', 'You have spent your life in service to a temple, learning sacred rites and providing sacrifices to the god or gods you worship. Serving the gods and discovering their sacred works will guide you to greatness.'),
('Charlatan', 'Youre an expert in manipulation, prone to exaggeration and more than happy to profit from it. Bending the truth and turning allies against each other will lead to greater success down the road.'),
('Criminal', 'You have a history of breaking the law and survive by leveraging less-than-legal connections. Profiting from criminal enterprise will lead to greater opportunities in the future.'),
('Entertainer', 'You live to sway and subvert your audience, engaging common crowds and high society alike. Preserving art and bringing joy to the hapless and downtrodden heightens your charismatic aura.'),
('Folk Hero', 'Youre a champion of the common people, challenging tyrants and monsters to protect the helpless. Saving innocents in imminent danger will make your legend grow.'),
('Guild Artisean', 'Your skill in a particular craft has earned you membership in a mercantile guild, offering privileges and protection while engaging in your art. Repairing and discovering rare crafts will bring new inspiration.'),
('Noble', 'You were raised in a family among the social elite, accustomed to power and privilege. Accumulating renown, power, and loyalty will raise your status.'),
('Outlander', 'You grew up in the wilds, learning to survive far from the comforts of civilisation. Surviving unusual hazards of the wild will enhance your prowess and understanding.'),
('Sage', 'You are curious and well-read, with an unending thirst for knowledge. Learning about rare lore of the world will inspire you to put this knowledge to greater purpose.'),
('Soldier', 'You are trained in battlefield tactics and combat, having served in a militia, mercenary company, or officer corps. Show smart tactics and bravery on the battlefield to enhance your prowess.'),
('Urchin', 'After surviving a poor and bleak childhood, you know how to make the most out of very little. Using your street smarts bolsters your spirit for the journey ahead.');
